
//  utils

function replaceHtml(str, match, replaceFn) {
  var re = new RegExp(match, 'gi');
  return str.replace(/([^<>]+)(?=<[^>]+>)/g, function(s, content){
    return  content.replace(re, replaceFn);
  });
}

function wrap(src, match) {
  return replaceHtml(src, match, function(str){
    return '<span class="pilcrow" >'+ str +'</span>';
  });
}

// main

function init(){
  console.log("Text init");

  // wrap pilcrows
  var content = document.body.innerHTML;
  document.body.innerHTML = wrap(content, '¶');
  let pilcrows = document.querySelectorAll('.pilcrow');
  pilcrows.forEach((pilcrow, idx) => {
    pilcrow.id = "pilcrow-" + idx;
    // to debug slides ids :
    // pilcrow.textContent = pilcrow.textContent + " " + idx
  })


  // insert timer bar 
  var bar =  `<div id="bar"><span></span></div>`;
  document.body.insertAdjacentHTML("beforeend", bar);


  // insert nav
  var nav = `<nav>    
    <button id="left"> ←</button> 
    <button id="right">→</button>
  </nav>`;
  document.body.insertAdjacentHTML("beforebegin", nav);

  function bindKeys(e){
		if(e.key == "ArrowLeft" || e.key == "ArrowRight" || e.key == "Enter") e.preventDefault();
		if (e.key == "ArrowLeft") {
      parent.postMessage({
        'action' : "left"
      }, "*")
    }
		if (e.key == "ArrowRight") {
      parent.postMessage({
        'action' : "right"
      }, "*")
    }
		if (e.key == "Enter") {
      parent.postMessage({
        'action' : "start"
      }, "*")
    }
		if (e.key == "Escape") {
      parent.postMessage({
        'action' : "toggleGrid"
      }, "*")
    }
	}

	// navigation au clavier (flèches directionelles)
	document.body.onkeydown = function(e){
		bindKeys(e)
	};


  var buttons = document.querySelectorAll("button");
  buttons.forEach((button) => { 
    button.onclick = () => {
      parent.postMessage({
        'action' : button.id
      }, "*")
    }
  })


  // remove originial <style> tag (generated by Zettlr HTML export) and inject two custom stylesheets
  let stylesheets = ["css/fonts/source/source.css", "css/text.css"];
  var head  = document.getElementsByTagName('head')[0];
  stylesheets.forEach((href) => {
    var link  = document.createElement('link');
    link.rel  = 'stylesheet';
    link.type = 'text/css';
    link.href = href;
    head.appendChild(link);
  })
  let style = document.querySelector('style');
  if(style) style.parentElement.removeChild(style);
}